repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/cpplint/cpplint
  rev: 2.0.0
  hooks:
    - id: cpplint
      args:
        - --filter=-whitespace/line_length,-whitespace/parens
