name: Make

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

